---
title: '[GUN VIOLENCE] Incidents_by_state'
author: "1585107 이지인"
date: "2018년 12월 3일"
output: word_document
---

```{r setup, include=FALSE}
# 패키지 설치
library(tidyverse)
library(dplyr)
select <- dplyr::select
count<-dplyr::count
rename<-dplyr::rename
library(readr)
library(ggplot2)
library(viridis)
library(ggmap)
library(devtools)

# google map api key 코드 불러오기
if(!requireNamespace("devtools")) 
  install.packages("devtools") 
devtools::install_github("dkahle/ggmap", ref = "tidyup")
register_google(key  ="AIzaSyBetNxF3HvdWiER0i_lIHm3tAu2rj4mWpE")

# 경로지정
setwd("C:/Users/USER/Documents/Github/Gun-violence-in-the-US/JIIN")

# 원자료
df1.data <- read_csv("data/DATA1.csv") 
df2.data <- read_csv("data/DATA2.csv")
df3.data <- read_csv("data/DATA3.csv")
df4.data <- read_csv("data/DATA4.csv")
code.data <- read_csv("data/UScode.csv") #51개주 위도 경도 인구(2017) 규제
income.data <- read_csv("data/USincome.csv")

# 원자료 복사 
df1 <- df1.data
df2 <- df2.data
df3 <- df3.data
df4 <- df4.data
code <- code.data
income<- income.data

#지도불러오기 map_data
usmap <-map_data("state") 
( df1 <- df1 %>%
    rename(long=longitude, lat=latitude) ) # long, lat 변수 통일
( a <- df1 %>% 
    count(state) %>% 
    rename(acc=n) )         # acc 주별(51개) 사건 수 변수 
code <- code[,c(1,2,4,5,6)]
head(code)                  # state code lat long pop(인구)
( b <- full_join(code,a) )  

# 인구 수를 고려했을 때 사건 수 - 인구 100000명 당 사고 발생 횟수
# accidents per 100000:  acc_pop  
( b <- b %>%                # b - state code lat long pop acc acc_pop
    filter(!is.na(acc), !is.na(pop)) %>%
    mutate( acc_pop = round( (acc/pop)*100000 ) )  )    
( usmap1 <- usmap %>%
  tbl_df %>%
  rename(state = region) %>%    # state 변수 통일 
  select(long:state) )

# b1 - state acc acc_pop
( b1 <- b %>%
  mutate( state = tolower(state) ) %>%
  select( state, acc, acc_pop ) )             
# b2 - usmap + acc acc_pop 
( b2 <- right_join(usmap1, b1, by="state") )  

```

```{r cars}
```

```{r pressure, echo=TRUE}
# 인구대비 사고수가 많은 지역 순서대로 정렬해보았다.
b %>% arrange(desc(acc_pop)) 

# District of Columbia주에서 이상치 300이 넘는 값을 보이므로 제외하고 상위 10개주를 차트로 나타내보자.
b %>%
  filter(state != "District of Columbia",
         rank(desc(acc_pop)) < 11)%>%
  ggplot(aes(reorder(state,acc_pop),acc_pop,
             fill=acc_pop))+
  geom_bar(stat="identity") + 
  ylab(label = "Incidents")+
  xlab(label = "State") +
  scale_fill_gradient(low="yellow", high="red")+
  theme(axis.text.x = element_text(angle=30))

# 사고 수 가장 많은 지역인 DC 확대 지도에 
# 3년간 사고 발생지를 표시해보고자 한다.
# DC 정보 code lat long pop acc
b %>% filter(state=="District of Columbia") 

# DC발생 총기사고 long, lat 뽑아냄
c <- df1 %>% 
  filter(state=="District of Columbia") %>%
  select(long, lat) 

# DC 지도
dc<-map_data('county', region='district of columbia')
head(dc)

#인구대비 사고 수 많은 주 확대지도
ggplot(dc, aes(long,lat))+
  geom_polygon(aes(group=group),fill="lightblue",colour="grey50")+
  geom_point(aes(long,lat), data=c, colour="red", alpha=0.2)+
  coord_quickmap()

DC<-get_map("District of Columbia", zoom=12,
            maptype = "terrain")
ggmap(DC, extent="device") + 
  theme_void()+
  geom_point(aes(long,lat), data=c, colour="red", alpha=0.15)+
  ggtitle("District of Columbia") 

```
